export const enum ErrorCode {
  CONTRACTPARTNER_DOES_NOT_EXIST = 2, //
  CAPITALSOURCE_DOES_NOT_EXIST = 19, //
  CAPITALSOURCE_USE_OUT_OF_VALIDITY = 122, //
  CAPITALSOURCE_IS_NOT_SET = 127, //
  CONTRACTPARTNER_IS_NOT_SET = 128, //
  BOOKINGDATE_IN_WRONG_FORMAT = 130, //
  COMMENT_IS_NOT_SET = 131, //
  USERNAME_PASSWORD_WRONG = 134,
  ACCOUNT_IS_LOCKED = 138,
  AMOUNT_ZERO = 200, //
  LOGGED_OUT = 231,
  POSTING_ACCOUNT_NOT_SPECIFIED = 234,
  CONTRACTPARTNER_NO_LONGER_VALID = 235, //
  BOOKINGDATE_OUTSIDE_GROUP_ASSIGNMENT = 246, //
  CAPITALSOURCE_INVALID = 296, //
  SPLIT_ENTRIES_AMOUNT_IS_NOT_EQUALS_MONEYFLOW_AMOUNT = 299, //
  AMOUNT_TO_BIG = 376, //
  MEDIA_TYPE_UNKNOWN = 379,
}
